### ISSUE TITLE
Support tokio-postgres

### ISSUE THREAD

**Issue by tingfeng-key** [quietboil/include-sql#1]
Hello, can you add support for tokio-postgres library?

**Comment by quietboil** [comment]
Assuming you have seen [include-postgres-sql](https://crates.io/crates/include-postgres-sql), is what it provides not suitable because it is not async? Or is there some other reason?

**Note** that all database specific include-sql crates - like [include-sqlite-sql](https://crates.io/crates/include-sqlite-sql), [include-postgres-sql](https://crates.io/crates/include-postgres-sql), and [include-oracle-sql](https://crates.io/crates/include-oracle-sql) - exist mostly as examples, because they define certain API and thus, IMHO, opinionated. The idea was that while you can take and use any of those as-is, you most likely will create your own that matches your preferences as to how that API should look and be convenient for your access to the database.

**Comment by tingfeng-key** [comment]
> Assuming you have seen [include-postgres-sql](https://crates.io/crates/include-postgres-sql), is what it provides not suitable because it is not async? Or is there some other reason?

Yes, because `include-postgres-sql` relies on `postgres`, not `tokio-postgres`

**Comment by quietboil** [comment]
`include-postgres-sql` 0.1.5 (the latest) now supports `tokio-postgres`. This must be explicitly requested via `tokio` feature, i.e.:
```toml
[dependencies]
include-postgres-sql = { version = "0.1", features = ["tokio"] }
```
All generated methods are now `async` (well, sort of :wink:) and must be `await`-ed. Check [include-postgres-sql/examples/async](https://github.com/quietboil/include-postgres-sql/tree/master/examples/async) for some examples.

**Comment by tingfeng-key** [comment]
Thank you very much for your efforts so that I can start using it in my project now
